Products page
sdtorresl/innovaciones-web pull request #2
Opened 2020-05-04 06:36 UTC by saralesan

Products page created.

2020-05-07 16:49 UTC, sdtorresl commented on src/app/components/solutions/solutions.component.scss
> +    .blue-text {
Como esta clase puede ser reutilizada en otros componentes yo creo que conviene dejarla en los estilos principales en vez de los estilos del componente,

2020-05-07 16:50 UTC, sdtorresl commented on src/app/components/solutions/solutions.component.scss
> +        .blue-text {
Boostrap tiene clases especiales de márgenes mt-# mb-# etc. Tal vez conviene colocar estas clases para poder dejar "blue-text" una clase general.

2020-05-07 16:59 UTC, sdtorresl requested changes
Amor, creo que vas muy muy bien. Has mejorado muchísimo. Revisa los cambios y me cuentas si tienes dudas.

2020-05-07 16:59 UTC, sdtorresl commented on src/app/components/solutions/solutions.component.scss
> +                background: #FF326A;
Tal vez puedas utilizar una variable para este fondo.

2020-05-07 16:59 UTC, sdtorresl commented on src/app/components/solutions/solutions.component.scss
> +}
Es conveniente dejar una linea extra vacía al final de todo código. Si averiguas por qué, te doy un helado <3

2020-05-07 16:59 UTC, sdtorresl commented on src/app/components/solutions/solutions.component.scss
> +                position: absolute;
Este position definitivamente no fue conveniente.

2020-05-07 16:59 UTC, sdtorresl commented on src/app/components/solutions/solutions.component.html
> +            <div class="price">Desde $5.000.000</div>
Hay una forma en Angular para dar estilo y formato a las monedas. Se llaman pipes, acuérdame y te digo como se hace.

2020-05-07 16:59 UTC, sdtorresl commented on src/app/components/solutions/solutions.component.html
> +    <div id="section-4">
En HTML5 hay una etiqueta que se llama section, úsala. Trata de que tus IDs digan lo que contiene o lo que hace.

2020-11-11 03:18 UTC, saralesan commented on src/app/components/solutions/solutions.component.scss
> +}
Se deja por que algunos editores de texto no hacen salto de linea para mostrar sus comandos y demas, por lo cual queda una cosa encima de la otra.

Mi Helado *.*

2020-11-11 03:18 UTC, saralesan commented on src/app/components/solutions/solutions.component.scss
> +}
Done

2020-11-11 03:19 UTC, saralesan commented on src/app/components/solutions/solutions.component.scss
> +                position: absolute;
Price removed, Done.

2020-11-11 03:59 UTC, saralesan commented on src/app/components/solutions/solutions.component.html
> +    <div id="section-4">
Done.

2020-11-11 22:07 UTC, sdtorresl approved these changes

2020-11-11 22:08 UTC, merged